name: NPM Publish

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - rich-text-editor

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      # Go into each package folder and publish
      - name: Publish ${{ matrix.package }}
        working-directory: ./${{ matrix.package }}
        run: |
          npm install
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
