# TEMPLATE: Copy this file and rename it to publish-YOUR-PACKAGE-NAME.yml
# Replace ALL instances of YOUR_PACKAGE_NAME with your actual package folder name
# Replace YOUR_NPM_PACKAGE_NAME with the name in your package.json
# Replace YOUR_PACKAGE_DESCRIPTION with a brief description

name: Publish YOUR_NPM_PACKAGE_NAME to NPM

on:
  push:
    branches: [ main, master ]
    paths:
      - 'YOUR_PACKAGE_NAME/**'  # Only run when files in YOUR_PACKAGE_NAME folder change
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for proper git operations
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-YOUR_PACKAGE_NAME-${{ hashFiles('YOUR_PACKAGE_NAME/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-YOUR_PACKAGE_NAME-
          ${{ runner.os }}-node-
          
    - name: Install dependencies
      run: |
        cd YOUR_PACKAGE_NAME
        npm ci
        
    - name: Run tests (if available)
      run: |
        cd YOUR_PACKAGE_NAME
        if npm run test --if-present; then
          echo "Tests passed or no tests defined"
        else
          echo "Tests failed, but continuing..."
        fi
      continue-on-error: true
        
    - name: Build package
      run: |
        cd YOUR_PACKAGE_NAME
        npm run build
        
    - name: Check if package exists on NPM
      id: check-npm
      run: |
        cd YOUR_PACKAGE_NAME
        PACKAGE_NAME=$(node -p "require('./package.json').name")
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        
        echo "Package: $PACKAGE_NAME"
        echo "Current version: $CURRENT_VERSION"
        
        # Check if this version already exists on NPM
        if npm view $PACKAGE_NAME@$CURRENT_VERSION version 2>/dev/null; then
          echo "Version $CURRENT_VERSION already exists on NPM, will bump version"
          echo "should_bump=true" >> $GITHUB_OUTPUT
        else
          echo "Version $CURRENT_VERSION does not exist on NPM, will publish as-is"
          echo "should_bump=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Bump version (if needed)
      id: version
      if: steps.check-npm.outputs.should_bump == 'true'
      run: |
        cd YOUR_PACKAGE_NAME
        # Get current version
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "Current version: $CURRENT_VERSION"
        
        # Bump patch version automatically
        npm version patch --no-git-tag-version
        
        # Get new version
        NEW_VERSION=$(node -p "require('./package.json').version")
        echo "New version: $NEW_VERSION"
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "version_bumped=true" >> $GITHUB_OUTPUT
        
    - name: Get current version (if not bumped)
      id: current-version
      if: steps.check-npm.outputs.should_bump == 'false'
      run: |
        cd YOUR_PACKAGE_NAME
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "Using current version: $CURRENT_VERSION"
        echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "version_bumped=false" >> $GITHUB_OUTPUT
        
    - name: Commit version bump
      if: steps.version.outputs.version_bumped == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add YOUR_PACKAGE_NAME/package.json
        git diff --staged --quiet || git commit -m "Bump YOUR_NPM_PACKAGE_NAME version to ${{ steps.version.outputs.new_version }} [skip ci]"
        
    - name: Push version bump
      if: steps.version.outputs.version_bumped == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        
    - name: Publish to NPM
      run: |
        cd YOUR_PACKAGE_NAME
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create Git Tag
      run: |
        cd YOUR_PACKAGE_NAME
        VERSION=${{ steps.version.outputs.new_version || steps.current-version.outputs.new_version }}
        PACKAGE_NAME=$(node -p "require('./package.json').name")
        git tag $PACKAGE_NAME-v$VERSION
        git push origin $PACKAGE_NAME-v$VERSION
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: YOUR_NPM_PACKAGE_NAME-v${{ steps.version.outputs.new_version || steps.current-version.outputs.new_version }}
        name: YOUR_NPM_PACKAGE_NAME v${{ steps.version.outputs.new_version || steps.current-version.outputs.new_version }}
        body: |
          ## 🚀 YOUR_NPM_PACKAGE_NAME v${{ steps.version.outputs.new_version || steps.current-version.outputs.new_version }}
          
          YOUR_PACKAGE_DESCRIPTION
          
          ### 📦 Installation
          ```bash
          npm install YOUR_NPM_PACKAGE_NAME
          ```
          
          ### 🔗 Links
          - [NPM Package](https://www.npmjs.com/package/YOUR_NPM_PACKAGE_NAME)
          - [Documentation](https://github.com/webakash1806/devi-extra-package#readme)
          
          ### 📝 What's Changed in YOUR_PACKAGE_NAME
          - Automatic release for YOUR_NPM_PACKAGE_NAME version ${{ steps.version.outputs.new_version || steps.current-version.outputs.new_version }}
          - Package published to NPM registry
          
          ### ✨ Features
          - Add your package features here
          - Feature 2
          - Feature 3
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
